tests/nixos/authorization: newer nixpkgs wants experimental-features to be a list
Not an issue with the nixpkgs of this flake, but with nixos-unstable
that is used by the Hydra to evaluate Lix:

    error: A definition for option `nodes.machine.nix.settings.experimental-features' is not of type `list of string'. TypeError: Definition values:
    - In `/nix/store/r0qd6c3dfnj6xr0dpk0i5q459p396jsl-source/tests/nixos/authorization.nix': "nix-command"

See https://hydra.afnix.fr/jobset/lix/main

Change-Id: Id889ab449754c721fb9cc96e3888426757703273