parser: improve error message for missing semicolon in let/{}
In the same vein as be18b7dc2¹.

Before:
  error: syntax error, expecting ';'

After:
  error: syntax error, expecting ';' to end binding

[1]: be18b7dc25da54ada1d102993a17ac27afbca5e4

Change-Id: Iffbcb113d2b892a50c646c9875e970376a6a6964